### ISSUE TITLE
patterns.vektor-inc.co.jp のパターンを読み込んで使えるようにする

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-block-patterns#100]
https://github.com/vektor-inc/vk-patterns/issues/165

↑ の後で実装

VK Pattern Library でお気に入りに登録したパターンを自分の編集画面で直接呼び出せるようにする機能です。

* VK Pattern Library お気に入りという名のパターンカテゴリを作る
* VK Pattern Library からパターン情報を取得して「VK Pattern Library お気に入り」のカテゴリのパターンとして登録する
* 取得するパターンはユーザーがお気に入りに登録したパターンのみ

認証関連仕様案
* ライセンスキーは VK Blocks Pro に登録済みの情報を使えば良いのでは？
* VK Pattern Library のユーザー情報に有効なライセンスキー情報をユーザーメタに保存させる
* クライアントからリクエストされたライセンスキーと合致する VK Pattern Libraryのユーザーを抽出
* そのユーザーが保存しているお気に入り情報を取得して、そのパターンを返す

**Comment by drill-lancer** [comment]
@kurudrive 
下記の感じでいかがでしょうか？

1. VWS から有効期限が残っているライセンスキーの配列をパターンライブラリの権限と同時に API で送信
　（↑お客ごとにライセンスキー買っている人がいたような・・・）
    一覧は[ライセンスキーを羅列するコード](https://github.com/vektor-inc/lightning-pro-child-vws/blob/master/woocommerce/myaccount/display-licensekey.php)があったのでそれを参考に

2. パターンライブラリの権限情報と同時に何らかの形でライセンスキーをパターンライブラリ上のユーザーメタに格納

3. このプラグインからライセンスキーを認証してパターンライブラリ上でライセンスキーを特定してそのユーザーのパターンを返す
   （[get_users](https://wpdocs.osdn.jp/%E9%96%A2%E6%95%B0%E3%83%AA%E3%83%95%E3%82%A1%E3%83%AC%E3%83%B3%E3%82%B9/get_users)）を使うことになるため配列は使えず一個一個フィールドに格納する形になりそうです。）

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございました。
