### ISSUE TITLE
プラグイン内のパターンの読み込みをオフにするとCSSも読み込まなくなるので表示が崩れる

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-block-patterns#108]
確認方法

1. パターンカテゴリ「カラム」の中でカラムの画像・レイアウトが左右交互になるパターンをを配置
2. 設定 > VK Block Patterns でこのブロックのパターンを非表示に設定
3. 画像・レイアウトが交互にならなくなる

CSSの読み込み部分はジェネレーターで行っているので該当箇所のファイル変更は基本できない。
なので、パターン読み込み停止の設定になっていたら別途CSSファイルを読み込む方が楽だと思います。

**Comment by drill-lancer** [comment]
まーじされたので Close
