### ISSUE TITLE
【お知らせ待ち】デフォルトパターン非表示機能 / お気に入り連携機能

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-block-patterns#120]
https://github.com/vektor-inc/vk-block-patterns/issues/119 の後にお知らせ記事よろしくお願いいたします。

**Comment by kaorock72** [comment]
@kurudrive 
お疲れさまです！お知らせ記事を書くにあたり、説明をどこにどう書くか悩みますが
以下のような感じはいかがでしょうか、、？

* デフォルトパターン設定とVK Pattern Library 設定の機能説明は下記ページに書く
https://www.vektor-inc.co.jp/service/wordpress-plugins/vk-block-patterns/
* 下記にも、お気に入りに登録したパターンをエディター上で直接呼び出せることを書きつつ、上記ページへのリンクも入れる
https://patterns.vektor-inc.co.jp/about/about-favorite/
*  そしてお知らせ記事を作成し公開する

**Comment by kurudrive** [comment]
- [ ] このプラグインのパターンを非表示にする
  → このプラグインのデフォルトパターンを非表示にする

---

# VK Block Patterns 紹介ページ（ vektor-inc.co.jp ）

## ブロックパターンとは？
## VK Block Patterns の主な機能

* 独自パターンの登録機能
* VK Block Patterns デフォルトパターン
* WordPress標準パターン / VK Block Patterns デフォルトパターンの停止機能
* VK Patterns Library との連携機能
  （詳しくはお気に入りページを見てね）

---

# お気に入り機能紹介ページ

## 何ができる

* お気に入りに登録して、後から絞り込んで表示
* お気に入りパターンを自分のWordPressの編集画面に直接読み込んで利用

## 使い方

* ユーザー登録
* お気に入り登録・解除
* 絞り込み表示方法
* VK Block Patterns との連携方法

---

# お知らせ記事

## VK Block Patterns でデフォルトパターン停止機能を追加しました。

→ co.jp のページ内にリンク（ Link Target Controller でリダイレクト ）

## VK Pattern Library のお気に入りパターンを編集画面で直接呼び出せるようになりました。
→ patterns.vektor-inc.co.jp の "お気に入りパターンを自分のWordPressの編集画面に直接読み込んで利用
" にリダイレクト

**Comment by kurudrive** [comment]
@kaorock72 おまたせしました。管理画面アップデート完了しました！

**Comment by kaorock72** [comment]
@kurudrive ありがとうございます、かしこまりました！

**Comment by kaorock72** [comment]
@kurudrive 
以下、新規ページで一旦作成しました、非公開です。
お手すきの時にご確認よろしくお願いします！

最終的に各現在のページへ反映させる予定です。

VK Block Patterns 紹介ページ
（動画は内容的に少し古いかなと感じたので、ひとまず埋め込みませんでした）
https://www.vektor-inc.co.jp/service/wordpress-plugins/new_vk-block-patterns/

お気に入り機能紹介ページ
https://patterns.vektor-inc.co.jp/about/new_about-favorite/

**Comment by kurudrive** [comment]
@kaorock72 ありがとうございます。必要に応じて調整しました！

**Comment by kaorock72** [comment]
お知らせ公開と各シェア完了したのでクローズいたします
