### ISSUE TITLE
vbp_get_pattern_api_data が init フックで毎回リクエストをしており負荷が高い

### ISSUE THREAD

**Issue by fumikito** [vektor-inc/vk-block-patterns#148]
ここで `init` フックを使って前リクエストに対し、 `vbp_register_favorite_patterns` が登録されています。

https://github.com/vektor-inc/vk-block-patterns/blob/0635abcb81e77439d126d57aad363cf146c56e14/favorite-patterns/favorite-patterns.php#L100

そしてここで APIデータを取得とありますが、

https://github.com/vektor-inc/vk-block-patterns/blob/0635abcb81e77439d126d57aad363cf146c56e14/favorite-patterns/favorite-patterns.php#L37

中でメールアドレスの状態をチェックし、外部へPOSTしているようです。
https://github.com/vektor-inc/vk-block-patterns/blob/0635abcb81e77439d126d57aad363cf146c56e14/favorite-patterns/favorite-patterns.php#L16-L29

この処理は全リクエストで走ってしまうので、かなり重く、キャッシュするなりした方がよいのでは、と考えます。

**Comment by kurudrive** [comment]
@fumikito ふぁー！恐縮でございます！
アドバイスありがとうございます。確認、調整させていただきます！

**Comment by kurudrive** [comment]
@fumikito すみません！ウチのスタッフと間違えてアサインしてしまってました🙏

**Comment by kurudrive** [comment]
- [ ] キャッシュを使うようにする
- [ ] APIに投げるデータの見直し

**Comment by drill-lancer** [comment]
とりあえず完了したっぽいので Close
