### ISSUE TITLE
【確認待ち】関数名が不適切なので変更したいデス。

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-block-patterns#149]
https://github.com/vektor-inc/vk-block-patterns/blob/7570b365ab064d7381f2e457b7f568da1292da04/favorite-patterns/favorite-patterns.php#L36

お気に入り以外のパターンも読み込む処理なのに favarite になっている

**Comment by drill-lancer** [comment]
関連するプルリクがマージされたようなので Close
