### ISSUE TITLE
【確認待ち】APIに投げるデータに問題があるので変更する必要がある

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-block-patterns#151]
メールアドレスを素で投げているのはセキュリティ面でまずくないか？

https://github.com/vektor-inc/vk-block-patterns/issues/148

**Comment by mthaichi** [comment]
@kurudrive @drill-lancer 今更ながらで、誠に申し訳ないのですが、メールアドレスを投げているのはセキュリティ面でどのように問題でしょうか。リクエストはPOSTメソッドで投げられるので、通信内容はSSLで暗号化されると思います。

具体的にどのような悪用が考えられますか。

たとえば、メールアドレスを投げて、個人情報などその人しか知り得ない情報をAPIが返してくるならば、それは問題です。メールアドレスではなく、何らかのキーを発行してそれを入力してもらうといったことが必要・・・といった感じで判断できます。

今回の場合、メールアドレスを投げて返ってくるのはパターンなので、そんなに問題ないのかなと感じますが、いかがでしょうか。パターン以外にやばいものを返していますか？

今になって言うなよですね。本当にすみません。

**Comment by kurudrive** [comment]
@mthaichi なんとなく指摘を受けただけなので、実際には僕も把握していないのですが、メールアドレスが確認できる状態で通信すると、メールアドレス＝ログインid なので、なるべくログインIDはわからない方がいいよね 的な事ではないかなと。

**Comment by mthaichi** [comment]
> @mthaichi なんとなく指摘を受けただけなので、実際には僕も把握していないのですが、メールアドレスが確認できる状態で通信すると、メールアドレス＝ログインid なので、なるべくログインIDはわからない方がいいよね 的な事ではないかなと。

であれば、対応する必要はないと考えます。

・そもそもSSLで通信は暗号化されています。
・REST APIでユーザーIDとパスワードを投げて、サーバーが認証して何かを返すという仕組みは多くあります。
ユーザーIDを送信している事自体は何ら問題がないと考えます。何らかのメールアドレスを使ってAPIを叩きに行って、個人情報的なものが返ってくるなら問題ですが、今回はブロックパターンなので、そんなに問題ではないかなと思います。
・SSLのことは置いておくとして、プラグイン側に暗号化のキーが書いてあるので、ソースを読めば、簡単に復号できてしまうのでは？  あまり意味がない気がします。

「どんなパターンを使っているか絶対知られたくない」という人が多くいれば、それは問題ですが、そんな人はあまりいないように感じます。

本当、今さらながらで重ね重ね申し訳ございません。

**Comment by mthaichi** [comment]
> @mthaichi なんとなく指摘を受けただけなので、実際には僕も把握していないのですが、メールアドレスが確認できる状態で通信すると、メールアドレス＝ログインid なので、なるべくログインIDはわからない方がいいよね 的な事ではないかなと。

@kurudrive であれば、対応する必要はないと考えます。

・そもそもSSLで通信は暗号化されています。
・REST APIでユーザーIDとパスワードを投げて、サーバーが認証して何かを返すという仕組みは多くあります。
ユーザーIDを送信している事自体は何ら問題がないと考えます。何らかのメールアドレスを使ってAPIを叩きに行って、個人情報的なものが返ってくるなら問題ですが、今回はブロックパターンなので、そんなに問題ではないかなと思います。
・SSLのことは置いておくとして、プラグイン側に暗号化のキーが書いてあるので、ソースを読めば、簡単に復号できてしまうのでは？  あまり意味がない気がします。

「どんなパターンを使っているか絶対知られたくない」という人が多くいれば、それは問題ですが、そんな人はあまりいないように感じます。

本当、今さらながらで重ね重ね申し訳ございません。

**Comment by drill-lancer** [comment]
一旦現状で様子見するため Close
