### ISSUE TITLE
【確認待ち】キャッシュをクリアするタイミングを変更する

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-block-patterns#152]
ユーザーがお気に入り登録して、自分のサイトの戻ってきた時に、手動でクリアしないと反映されないので、
「連携がちゃんと反応しない」と思われてしまう。

* 記事の編集画面を開いたタイミングでAPIを叩く
* 記事編集画面を最後に開いてから一定時間でキャッシュをクリアする

あたりが妥当ではないかなと思います。

関連

* https://github.com/vektor-inc/vk-block-patterns/issues/148

**Comment by drill-lancer** [comment]
@kurudrive 
１日１記事ペースの方ならそれでも良いかもしれませんが、
１日に数時間以内に10ページ・100ページつくる人がいる場合、
記事編集画面が開かれるたびに API を走らされるとわざわざキャッシュ化した意味が薄れる気がします。

そもそもそれが必要な頻度でお気に入りを改変する人が存在するのかが疑問です。

個人的には編集画面にパターンのキャッシュクリアボタンを追加するのが妥当だと思います。

**Comment by kurudrive** [comment]
@drill-lancer とりあえず @mthaichi さんと話してたのは、

現状の仕様ではお気に入りを登録して戻ってきた人が、キャッシュをクリアしないといけない事に気づかないので、お気に入りに登録したものが出てこない＝ **不具合** とみなされてしまう点です。

> そもそもそれが必要な頻度でお気に入りを改変する人が存在するのかが疑問です。

で、頻度が多くないからこそ、クリアしないといけないという事をすぐ忘れてしまって「反映されんやんけ！」となってしまう事が問題だなと思うわけですよ。

キャッシュ化した意味は薄れるのですが、そもそも以前の仕様だと、編集画面ではなく「公開ページを一般ユーザーが閲覧しただけでAPIが走ってしまう」という状態でとんでもない負荷がかかるのが最大の問題だったので、記事編集画面で走るようにするだけでも何万分の１レベルには低減されると思います。

ではキャッシュ化が必要ではないかというとそうではなくって、
編集画面のリロードの度に走るのはやはり無駄なので一定数はキャッシュを使いたい
前回のAPIアクセスから１時間とか経ってる場合はAPIを再度リクエストするとか？
頻度は要検討

まぁそのあたりも踏まえて仕様をどうするかは月曜に検討しましょうという話でした。
