### ISSUE TITLE
パターン→セクションPR→カラムバナーとカラムバナーフィットの背景色がつくようになったので、調整が必要かも？

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-block-patterns#156]
特定の環境だけなので気のせいな気がしてきました、、！
<s>パターン→セクションPR→カラムバナーとカラムバナーフィットを配置するとVKボタンの背景色に標準色が設定されていて、背景色がついてしまっている？（例えばDarkなどの他の色なら問題無し）</s>

**【原因】**
標準色だと、! important指定があるので、background-color: unset;　が負けてしまい標準色がついてしまう。

**【解決策】**
- 標準色primary じゃなく、他のDarkなどの色にする。
- もしくはCSSで強く書く？

もしかしたら勘違いかもしれないので、一旦相談待ちにします

![スクリーンショット 2022-10-25 10 23 20](https://user-images.githubusercontent.com/5525368/197660358-88f5adba-8dab-4848-aabf-4d1ef31618d2.png)

>  :root .has-vk-color-primary-background-color {
>      background-color: var(--wp--preset--color--vk-color-primary) !important;
>  }

**Comment by goutetsuguma** [comment]
修正ありがとうございます！Closeしますね

**Comment by kurudrive** [comment]
@goutetsuguma あー、一週間以上も前に issue 上がってたのかぁ...
そしてこの issue に気づかずに原因調査に １時間くらい使ってしまった...orz
