### ISSUE TITLE
自分で登録したパターンを特定の投稿タイプの初期パターンとして挿入できる機能を追加

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-block-patterns#166]
[ 1 ] 投稿タイプ vk-block-patterns の投稿編集ページに、メタボックスで

---

■ 投稿タイプの初期パターンでの使用
以下のプルダウンから投稿タイプを指定すると、指定した投稿タイプの初期パターンとして表示されるようになります。
[ 選択してください ▼ ]

---

みたいなのを作成し、このパターンを特定の投稿タイプの初期パターンとして登録するかどうか（投稿タイプ名）をカスタムフィールドに保存

[ 2 ] 初期パターンとして以下を参考に登録されるようにする

https://wp.me/p2AvED-pW1
```
register_block_pattern(
	'custom-pattern',
	array(
		'title'      => _x( 'Start post pattern', 'Block pattern title', 'gutenberg' ),
		'blockTypes' => array( 'core/paragraph', 'core/post-content' ),
		'postTypes'  => array( 'post' ),
		'content'    => '<!-- wp:paragraph -->
<p>A start post pattern</p>
<!-- /wp:paragraph -->',
	)
);
```

**Comment by kurudrive** [comment]
@doshimaf これ大嶋君やってみたい？
やってみたかったら @drill-lancer さんに何を参考にとっかかればいいか聞いてー。

「いやいや、パターンとかマーケティングとかそっちの方がやりたいっすー。」の場合はそっちやっていただいて構わないので、実装を @drill-lancer にお願いしちゃってー。

**Comment by doshimaf** [comment]
@kurudrive やってみます！
