### ISSUE TITLE
【お知らせ待ち】候補選択ではなく完全自動挿入機能が欲しい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-block-patterns#174]
## 現状問題点

* 選択しないといけない
* 配置ロックができない

## 完全自動＆ロックができると...

* 新規作成時に一手間少なくて済む
* カスタムフィールドを埋め込んで、従来通りAFCなどから値だけ入れさせられる

---

## 技術情報

https://training.vektor-inc.co.jp/courses/wordpress-customize/lessons/add-default-block-template/
https://developer.wordpress.org/block-editor/reference-guides/block-api/block-templates/

登録されたコンテンツを配列に分解しないといけないので、面倒そうだけどそのあたりは ChatGPT さんが良きに計らって変換コードを書いてくれないだろうか...

---

## 変更が必要なUI

現状の機能も状況によって有効なためイキ。

そのため、

* 新規投稿時に候補に表示する
* 新規投稿時に自動配置する

の選択をさせる必要がある

そして、自動配置の場合は $post_type_object->template_lock = 'all'; を指定するか選択できるようにする

ただ、$post_type_object->template_lock = 'all';  が単純にブロックのUIでポチポチロックするのと同じで、編集者が解除可能の場合はパターン作成時に手動で設定してもらえばいいからナシでもいいかも。とりあえず挙動確認してください。

**Comment by doshimaf** [comment]
@kurudrive 

* 候補表示と自動挿入を選択できるオプションの追加
* 新規作成時、自動挿入が選択されたパターンがあれば挿入（候補は表示されない）
* 自動挿入が選択されたパターンがなければ候補を表示

というところまで実装しました。

現状の課題は以下で、仕様上問題ないかどうか、解決案などがあれば教えていただきたいです。
* テンプレートロックを持つパターンがひとつでもあると、自動挿入が機能しない
->ロックに関するコードをコメントアウトすると挿入された。
* ひとつの投稿タイプに対して自動挿入が選択されたパターンが複数あると、最も古いものだけが挿入される
* 過去に追加していたパターンは、更新しないと候補に表示されない

登録されたパターンのコンテンツをテンプレート挿入専用の配列に変換する件については、下記記事を参考に変換せずにパターンのスラッグを登録して挿入する方法で実装しています。

https://wpengine.com/builders/block-templates/

**Comment by kurudrive** [comment]
> * テンプレートロックを持つパターンがひとつでもあると、自動挿入が機能しない
>   ->ロックに関するコードをコメントアウトすると挿入された。

→ ロックはブロック側で指定してもらうようにする（＝ロックのプルダウンは削除）
コンテンツの追加などはできてしまうがまぁしゃーない。
気が向いたらコアにissueで質問してくれてもええんやで。

> * ひとつの投稿タイプに対して自動挿入が選択されたパターンが複数あると、最も古いものだけが挿入される

→ 投稿タイプ選択プルダウンの下に注意文追加

> * 過去に追加していたパターンは、更新しないと候補に表示されない

→ 既存データについて
* 投稿タイプのみ指定されてる
→ 投稿タイプが保存してある & 自動挿入タイプ指定なし → show

**Comment by kurudrive** [comment]
@kaorock72 週明けにお知らせ記事よろしくお願いいたします (￣人￣)
https://twitter.com/kurudrive/status/1654434293991743488

あと、この機能に特化した定期 tweet 用画像が欲しいデス (￣人￣)
https://www.figma.com/file/5gDOnUpl0FG62ev3qCUW9y/VK-Dynamic-If-Block?node-id=0-1&t=cDEwGfBdWUhUMzM9-0
