### ISSUE TITLE
【確認待ち】.org のデプロイで vendor ファイルなど適切にデプロイされてない

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-block-patterns#190]
@drill-lancer これ最優先でよろしくお願いいたします。
※ 現状は安定版に戻してあるのでウルトラ急ぎじゃないですが、優先作業でよろしくお願いいたします。

1. 調整
2. readme.txt の stable のバージョンを上げずに、php ファイルの方だけバージョンアップ
3. タグプッシュ
4. VK Plugin Betatester 有効 & 設定画面からベータテストの対象プラグインを指定

でデプロイ版を確認してください。

**Comment by drill-lancer** [comment]
@kurudrive 
1.29.6 の時点で正常にリリース・デプロイされていると思われます。

**Comment by kurudrive** [comment]
@drill-lancer .org には 1.29.6 上がっているようですが、Beta Tester だと 1.29.2 までしか取得できないのですが何か心あたりありますか？

**Comment by kurudrive** [comment]
@drill-lancer あ、取得できました。　Check For Update で最新になりました。お騒がせしました。
ダッシュボード > 更新 では更新されないのね...。
