### ISSUE TITLE
 VK Block Patterns の初期パターン設定の「対象の投稿タイプ」と「パターンの追加方式」の動作

### ISSUE THREAD

**Issue by doshimaf** [vektor-inc/vk-block-patterns#195]
https://vws.vektor-inc.co.jp/forums/topic/vk-block-patterns-%e3%81%ae%e5%88%9d%e6%9c%9f%e3%83%91%e3%82%bf%e3%83%bc%e3%83%b3%e8%a8%ad%e5%ae%9a%e3%81%ae%e3%80%8c%e5%af%be%e8%b1%a1%e3%81%ae%e6%8a%95%e7%a8%bf%e3%82%bf%e3%82%a4%e3%83%97%e3%80%8d

1. 対象の投稿タイプ として 投稿 を選ぶと、そのパターンが 固定ページ で使えない。
2. パターンの追加方式 に 指定なし を選んでも、候補に表示 に戻ってしまう。

**Comment by doshimaf** [comment]
@kurudrive 
２については、1.27のアップデート以降に投稿タイプのみ保存してあって表示方式の指定がない場合の自動的に show にする処理で、自動でshowにする対象に空文字列の'Unspecified'が入っていたので修正しています。

**Comment by doshimaf** [comment]
@kurudrive
1について確認したところ、対象の投稿タイプ「投稿」に自動挿入するパターン（パターンA）の場合、固定ページで使えないのではなく、候補表示も自動挿入もできないという意図だと認識しています。
これは、パターンAに対して投稿にも固定ページにも自動挿入や候補表示できるようにしてほしいということでしょうか？

投稿用のパターンと固定ページ用のパターンを作ってもらうのが良いような気もしますが。

**Comment by kurudrive** [comment]
@doshimaf ありがとうございます。

1 については、例えば旧バージョンではパターンを登録すればどの投稿タイプでも呼び出せたのに、
デフォルト投稿機能がついてから、指定した投稿タイプでしか呼び出されなくなっています。

これは VK_Block_Patterns::register_block_patterns(); の中での、まず投稿タイプを限定して、その上でパターン登録しているのではないかと思います。

* ブロックパターンを登録して呼び出す機能
* 登録したブロックパターンを初期パターンとして自動挿入する機能

はそれぞれ独立した機能ですが、一つの  VK_Block_Patterns::register_block_patterns();  で処理してしまっている事もコードの可読性を下げていると思いますので、「パターンを登録して呼び出す機能（register_block_patterns）」と「自動挿入する機能」は別のメソッドにリファクタリングしてみてください。

**Comment by tt-uonuma-js** [comment]
対応、ありがとうございます。

私の使い方と要望は以下の通りです。

標準投稿・固定ページ・カスタム投稿タイプのどれでも使える汎用的なブロックパターンをいろいろ作って、お客様のサイトでもお使いいただいています。

ですので、通常は自動挿入や候補表示の必要がありません。

例えば、工務店の施工実績をカスタム投稿タイプで作るとき、自動挿入や候補表示を使ってひな型がドカーンと入るようにできると便利だと思います。
