### ISSUE TITLE
【フォーラム】メディアの画像が別の月のフォルダに入ってしまいます

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-block-patterns#203]
わたしの環境でもみたところ、VK Block Patterns 有効化にしていて、メディアから画像をアップすると特定の別の年月フォルダに入ってしまうようでしたので、issueをたてさせていただきます(固定ページなどから画像を入れた場合は問題ありません。)

いったんAssigneesには開発者メンバーの方を入れさせていただきました。
もし調査する場合はかぶるといけませんのでAssigneesを自分だけにして調査するか、調査開始しますなどのコメントをかいておくと良いと思います。よろしくお願いします。

https://vws.vektor-inc.co.jp/forums/topic/%e3%83%a1%e3%83%87%e3%82%a3%e3%82%a2%e3%81%ae%e7%94%bb%e5%83%8f%e3%81%8c%e5%88%a5%e3%81%ae%e6%9c%88%e3%81%ae%e3%83%95%e3%82%a9%e3%83%ab%e3%83%80%e3%81%ab%e5%85%a5%e3%81%a3%e3%81%a6%e3%81%97%e3%81%be

**Comment by kurudrive** [comment]
@goutetsuguma これ新規サイトで発生？既存サイト？

**Comment by goutetsuguma** [comment]
@kurudrive 既存のサイトで発生しました。

**Comment by kurudrive** [comment]
@goutetsuguma たぶん直ってると思いますので確認して問題なければcloseしてくださいー。

**Comment by goutetsuguma** [comment]
治っているのを確認しましたので、Closeしますー
