### ISSUE TITLE
Lightning の無料版のデモサイトでだけパターン連携するとやたら遅くなるので原因調査

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-block-patterns#206]
該当サイト : https://demo.dev3.biz/lightning-g3

## 発生手順

1. 設定 > VK Block Patterns で vk-support@vektor-inc.co.jp など入力して保存
2. トップページを表示 -> 激遅になる

## 備考

* 他のサイト（同サーバー内の他デモサイトなど）では全く問題ない
* 連携アカウントを変更しても症状は同じ
* 該当サイトは 6.4 beta4 だが、他の 6.4  の環境でも発生しなかった
* ローカル環境に複製しても発生しなかった

**Comment by kurudrive** [comment]
@mthaichi これ何か原因検討つきますかね...（・ｗ・？

**Comment by mthaichi** [comment]
@kurudrive なかなかやっかいですね。ルートディレクトリにtest.phpとして以下のコードを置いて動かしてみました。
```
<?php
require_once './wp-blog-header.php';

$response = wp_remote_get('https://vektor-inc.co.jp/', array(
					'timeout' => 30,
					'sslverify' => false
				));

echo $response;
```

- このサイトのWordPressのwp_remote系関数だけ時間がかかる。（demo.dev3.biz内の他のWPは問題なし）
- エックスサーバー内のサイトだけ時間がかかる。
- このコンテンツを他サーバーに手動コピーで動かしてみたところ、レスポンスに問題はない。したがって、WordPressのバージョン起因ではない。
- wp_remote系関数は標準でcurl関数を使っているが、同サーバー内からcurl関数を使ってエックスサーバー内のホストの内容を取得してみたが、問題なく動く。
- サーバーの最初の応答は早い。しかし、コンテンツの受信に時間がかかる。

というところまで分かりましたが、根本原因までたどり着けておりません。
結構な謎です。

**Comment by mthaichi** [comment]
@kurudrive 暫定的な方法としては、
https://github.com/WordPress/wordpress-develop/blob/69a56e30f96333dd6de25c141428c7e7ced480d4/src/wp-includes/Requests/src/Requests.php#L141C1-L144C4

ここのところを

	const DEFAULT_TRANSPORTS = [
		Fsockopen::class => Fsockopen::class,
	];
と書き換えれば、とりあえずさくっと動くはずです。
これについて引っ掛けられそうな、フィルターフックとか見つからないので、私の力ではここまでです。すみません。

WordPressのバージョンを変えるか、
ゼロベースでWordPressをインストールして、All in one WP Migrationでインポートしたら、案外さくっとうごくかもしれません。

**Comment by mthaichi** [comment]
WP6.4.1で改善されたのでクローズ
