### ISSUE TITLE
【勉強会用】見出しのパターンを増やしたい

### ISSUE THREAD

**Issue by miminari** [vektor-inc/vk-block-patterns#28]
Trello　より移行　https://trello.com/c/GZBIdKo2/2189-%E8%A6%8B%E5%87%BA%E3%81%97%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3%E4%BE%8B

参考URL
https://twitter.com/pulpxstyle/status/1339363053096247296

**Comment by goutetsuguma** [comment]
メモ
https://patterns.vektor-inc.co.jp/vk-heading/

**Comment by kurudrive** [comment]
カスタム CSS ブロックが出来てからパターンライブラリの方で登録

**Comment by goutetsuguma** [comment]
【メモ】
4月の勉強会用：simple copy blockでコピーしてユーザーに持って帰ってもらえるようにVektorのブログに書く
https://www.notion.so/MTG-2023-2-9-2021-12-02-cb64c0c9efbd4eae8cfa17c9772b6e14
