### ISSUE TITLE
【確認待ち】5.8 RC1で有効化するとエディタ画面でJSエラーが28件出る

### ISSUE THREAD

**Issue by miminari** [vektor-inc/vk-block-patterns#34]
WordPress 5.8 RC1 のテスト中に気が付きました。

Twenty Twenty One + VK Blocks Pro + VK Block Pattern 
Lightning + VK Blocks Pro + VK Block Pattern + EXunit

どちらの組み合わせでも

> Block validation: Block validation failed for `vk-blocks/heading`

というJSエラーがコンソールで28件出ます。

**Comment by kurudrive** [comment]
VK 見出しブロック に問題があって Block Pattern に登録してある VK 見出しブロック が多分破損している系と思われます。 
なのでパターンに使ってた見出しブロックを先日いくつかWordPress標準には変更したけれど、 VK 見出しブロックの不具合自体はまだ原因調査・修正していない状態。

要そのあたり調査
