### ISSUE TITLE
Katawara で メディアカラム のレイアウトが崩れる

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-block-patterns#45]
![VK-Block-Patterns-1-6-0-でカラム系ブロックパターンなどを多数追加しました。-株式会社ベクトル](https://user-images.githubusercontent.com/3272660/127266469-848585f8-1831-4417-9972-6fdfbff8c32f.png)

**Comment by goutetsuguma** [comment]
@kurudrive 
わたしのローカルとデモサイトのKatawaraでメディアカラムを配置してみましたところ、崩れなかったのでご報告です。
2カラム、1カラムで確認しました。

**Comment by shimotmk** [comment]
(横から失礼します)
@goutetsuguma 

Katawaraで幅が600px〜781pxの時にカラム落ちが起きる様です。
https://www.vektor-inc.co.jp/product-update/vk-block-patterns-1-6-0-add-patterns/

上のほうでは発生しないのが不思議ですがbodyのfont-sizeが原因ですかね。
(cssに詳しくなく申し訳ないですが)
