### ISSUE TITLE
【お知らせ待ち】patterns.vektor-inc.co.jp へのリンクをつけたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-block-patterns#67]
こういうこういうのがあると良いと思うのですができます？

![スクリーンショット 2022-03-02 14 43 58](https://user-images.githubusercontent.com/3272660/156302627-2051f8e7-8e28-4713-b3bc-c3aba12a313c.png)

**Comment by shimotmk** [comment]
@kurudrive 
インサーターはReactで作られているので、ここにHTMLを追加するのは無理そうです
Gutenbergのインサーターパネル関連のコード
https://github.com/WordPress/gutenberg/blob/8029f73ff0d4066a5d3fd72fb5a7cff9b6a05b7e/packages/block-editor/src/components/inserter/pattern-panel.js

初期レンダリングで表示されるヘッダーのツールバー(下書き保存などの横)ならHTMLを追加できると思います
![header](https://user-images.githubusercontent.com/42362903/158745178-21d46703-a8f8-48d3-859c-1d3e82f6640e.png)

**Comment by kurudrive** [comment]
@shimotmk ほほう、なるほど！一度それでテスト実装してみてくださいー。

**Comment by shimotmk** [comment]
@kurudrive 
patterns.vektor-inc.co.jp へのリンクをテスト実装してみました！
ブランチ #70 

日本語以外では表示されません

TT1
![TT1](https://user-images.githubusercontent.com/42362903/158947894-9bdd4144-a590-4363-887f-595133b36048.png)

TT2 サイトエディター
![TT2-site-editor](https://user-images.githubusercontent.com/42362903/158947909-443c82ed-bd35-49c8-ae4c-aeaca4de5203.png)

ご確認お願いします！

**Comment by kurudrive** [comment]
@shimotmk ありがとうございます。さすがです。

場所が場所だけにこれ邪魔に思う人も残念ながら出てしまうと想定されるので、
お手数ですが、

- [ ] このリンクを非表示にする設定画面の追加お願いしたいです。
- [ ] プラグイン一覧から設定画面へのリンクの追加もお願いしたいです。

設定画面の中身はReactでお願いしたいです。

https://qiita.com/TetsuakiHamano/items/a562d34e9836c6ef81d5
https://developer.wordpress.org/block-editor/how-to-guides/data-basics/

**Comment by shimotmk** [comment]
@kurudrive
パターンディレクトリーへのリンクを表示するかどうかの管理画面に作ってみました
ブランチ #70
 
すでにある権限設定と同じオプション値を使うためには両方ともReact化するしかなかったので権限設定の方もReactで編集画面を作っています。
 
なおプラグイン一覧から設定画面へのリンクはすでに実装されていました
ご確認お願いします！

**Comment by kurudrive** [comment]
@kaorock72 

このリンクは、設定 > VK Block Patterns から非表示に変更する事ができます。

**Comment by kaorock72** [comment]
@kurudrive もう少し待てば翻訳が反映されますか？
反映されてからキャプチャ取ろうかなと思っています
<img width="872" alt="スクリーンショット 2022-04-08 14 39 09" src="https://user-images.githubusercontent.com/59037734/162371852-00f9317a-53e0-4a70-b2b6-96bb391ad639.png">

**Comment by kurudrive** [comment]
@kaorock72 翻訳わすれてました。

今しました。

で、先日とりさんが言ってたmorimayoさんのプラグインを使えばすぐに翻訳が落ちるのかな？

**Comment by kurudrive** [comment]
@kaorock72 

これかな

https://ja.wordpress.org/plugins/force-update-translations/

**Comment by kaorock72** [comment]
@kurudrive ありがとうございます！
プラグイン使ってみました
プラグイン一覧のVK Block Patternsから「翻訳を更新」をして
「翻訳ファイルをダウンロードしました: VK Block Patterns」となるのですが
赤枠部分が「エディターの設定」と翻訳されました。
何度かダウンロードはしてみています。もう少し試してみます、、
<img width="872" alt="スクリーンショット 2022-04-08 15 50 09" src="https://user-images.githubusercontent.com/59037734/162380384-6619ac43-22a1-46f3-9a16-17a7a7ed5a3b.png">

**Comment by kaorock72** [comment]
クローズするのを忘れていました、、
https://www.vektor-inc.co.jp/product-update/vk-block-patterns-1-16-1-add-vk-pattern-library-link/
お知らせ済みですので、完了とします。
