### ISSUE TITLE
管理画面の翻訳が効かないので修正したい (´；ω；｀)

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-block-patterns#86]
https://ja.wordpress.org/team/handbook/block-editor/how-to-guides/internationalization/
https://developer.wordpress.org/reference/functions/wp_set_script_translations/

@shimotmk 助けて！

**Comment by shimotmk** [comment]
なんとなく情報をまとめると
 
translate.wordpress.orgの翻訳ページにはjsの情報は入ってきていて翻訳されている
https://translate.wordpress.org/projects/wp-plugins/vk-block-patterns/dev/ja/default/
翻訳ファイルをエクスポートして見てもjsの情報は入っている
 
しかし配布されている翻訳
wp-content/languages/plugins/vk-block-patterns-ja.po
にはjsで翻訳するテキストが入っていないものがある
PHPの翻訳テキストは入っている
 
そしてjsのテキストは翻訳されない
 
コアのプラグインの翻訳はGlotPressを利用している
https://glotpress.blog/
 
ということでコアに問い合わせるしか無いかなと思うのですがコアのチケットが良いですかね
https://meta.trac.wordpress.org/
もしくはGlotPressにissue？
https://github.com/GlotPress/GlotPress
 
どこに問い合わせると気づいてもらいやすいかわかる方いたら教えていただけると嬉しいです〜

**Comment by shimotmk** [comment]
コアにチケット送りました
https://meta.trac.wordpress.org/ticket/6270

**Comment by kurudrive** [comment]
ん？いや、initで実行するとダメだから js の読み込み場所と同じにしたのか

@shimotmk ありがとうございました！
